name: dispatch-data-submission-guide-update
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["sennetconsortium/documentation", "hubmapconsortium/documentation"]
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"event_type": "data-submission-guide-update", "client_payload": {}}' \
          https://api.github.com/repos/${{ matrix.repo }}/dispatches
